inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "config/environments/**/*"
    - "config/routes.rb"
    - "config/application.rb"
    - "vendor/**/*"

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'code/test/**/*'
    - 'test/**/*'
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
